#!/bin/bash

if ! command -v "git-lfs" &> /dev/null
then
    echo "COMMAND "git lfs" could not be found"
    echo "Please install git-lfs support, see: https://git-lfs.github.com/"
    exit
fi

echo "Importing databases"
ddev import-db -d=v11 --src=.project/data/v11/db.sql.gz
ddev import-db -d=v12 --src=.project/data/v11/db.sql.gz