services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2faq\:
    resource: '../Classes/*'

  In2code\In2faq\Command\ImportFromIrfaqCommand:
    tags:
      - name: 'console.command'
        command: 'in2faq:importIrFaq'
        description: 'Imports records from EXT:irfaq'
        # not required, defaults to false
        hidden: false